// <auto-generated />
using System;
using ASMS.Repositories.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASMS.Repositories.Migrations
{
    [DbContext(typeof(AsmsContext))]
    [Migration("20251006152019_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASMS.Repositories.Entities.Box", b =>
                {
                    b.Property<string>("BoxCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CellCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("BoxCode")
                        .HasName("PK__Box__CB1C2B234E5BF880");

                    b.HasIndex("CellCode");

                    b.ToTable("Box", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Building", b =>
                {
                    b.Property<string>("BuildingCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Area")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BuildingName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("FloorQuantity")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("BuildingCode")
                        .HasName("PK__Building__D4DA0325478792F2");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Cell", b =>
                {
                    b.Property<string>("CellCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("RoomCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("CellCode")
                        .HasName("PK__Cell__F6994BB72E832EBC");

                    b.HasIndex("RoomCode");

                    b.ToTable("Cell", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Customer", b =>
                {
                    b.Property<string>("CustomerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CustomerCode")
                        .HasName("PK__Customer__0667852064317DAB");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Employee", b =>
                {
                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BuildingCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("EmployeeRoleId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeRoleID");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("EmployeeCode")
                        .HasName("PK__Employee__1F6425494C433023");

                    b.HasIndex("BuildingCode");

                    b.HasIndex("EmployeeRoleId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeRoleId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeRoleID");

                    b.Property<string>("EmployeeRole1")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("EmployeeRole");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.HasKey("EmployeeRoleId")
                        .HasName("PK__Employee__3461868632E1BC62");

                    b.ToTable("EmployeeRole", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Floor", b =>
                {
                    b.Property<string>("FloorCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BuildingCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("FloorCode")
                        .HasName("PK__Floor__394E956B4D721C8D");

                    b.HasIndex("BuildingCode");

                    b.ToTable("Floor", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Order", b =>
                {
                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("DepositDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("UnpaidAmount")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("OrderCode")
                        .HasName("PK__Order__999B52280722FFBF");

                    b.HasIndex("CustomerCode");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailID");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BoxCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Quantity")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoomCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__OrderDet__D3B9D30CF88C1100");

                    b.HasIndex("BoxCode");

                    b.HasIndex("OrderCode");

                    b.HasIndex("RoomCode");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.PaymentHistory", b =>
                {
                    b.Property<string>("PaymentHistoryCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentPlatform")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PaymentHistoryCode")
                        .HasName("PK__PaymentH__F83BEDA4BA9A5F87");

                    b.HasIndex("OrderCode");

                    b.ToTable("PaymentHistory", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Room", b =>
                {
                    b.Property<string>("RoomCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FloorCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("RoomTypeID");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("RoomCode")
                        .HasName("PK__Room__4F9D5230A600B6D9");

                    b.HasIndex("FloorCode");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("RoomTypeID");

                    b.Property<string>("RoomTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoomTypeId")
                        .HasName("PK__RoomType__BCC896110CC5D09F");

                    b.ToTable("RoomType", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ServiceId")
                        .HasName("PK__Service__C51BB0EAAB265F58");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.TrackingHistory", b =>
                {
                    b.Property<int>("TrackingHistoryId")
                        .HasColumnType("int")
                        .HasColumnName("TrackingHistoryID");

                    b.Property<string>("ActionType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly?>("CreateAt")
                        .HasColumnType("date");

                    b.Property<string>("CurrentAssign")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NextAssign")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TrackingHistoryId")
                        .HasName("PK__Tracking__26DB07A7040C89E7");

                    b.HasIndex("OrderCode");

                    b.ToTable("TrackingHistory", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowStep", b =>
                {
                    b.Property<int>("WorkflowStepId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowStepID");

                    b.Property<int?>("StepNumber")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowTemplateID");

                    b.HasKey("WorkflowStepId")
                        .HasName("PK__Workflow__3612140149770D3B");

                    b.HasIndex("WorkflowTemplateId");

                    b.ToTable("WorkflowStep", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowTemplate", b =>
                {
                    b.Property<int>("WorkflowTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowTemplateID");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("RoomTypeID");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("WorkflowTemplateId")
                        .HasName("PK__Workflow__96E60A37CE12083A");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("WorkflowTemplate", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Box", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Cell", "CellCodeNavigation")
                        .WithMany("Boxes")
                        .HasForeignKey("CellCode")
                        .HasConstraintName("FK__Box__CellCode__619B8048");

                    b.Navigation("CellCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Cell", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Room", "RoomCodeNavigation")
                        .WithMany("Cells")
                        .HasForeignKey("RoomCode")
                        .HasConstraintName("FK__Cell__RoomCode__59FA5E80");

                    b.Navigation("RoomCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Employee", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Building", "BuildingCodeNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("BuildingCode")
                        .HasConstraintName("FK__Employee__Buildi__71D1E811");

                    b.HasOne("ASMS.Repositories.Entities.EmployeeRole", "EmployeeRole")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeRoleId")
                        .HasConstraintName("FK__Employee__Employ__70DDC3D8");

                    b.Navigation("BuildingCodeNavigation");

                    b.Navigation("EmployeeRole");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Floor", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Building", "BuildingCodeNavigation")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingCode")
                        .HasConstraintName("FK__Floor__BuildingC__534D60F1");

                    b.Navigation("BuildingCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Order", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Customer", "CustomerCodeNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerCode")
                        .HasConstraintName("FK__Order__CustomerC__5EBF139D");

                    b.Navigation("CustomerCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.OrderDetail", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Box", "BoxCodeNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("BoxCode")
                        .HasConstraintName("FK__OrderDeta__BoxCo__68487DD7");

                    b.HasOne("ASMS.Repositories.Entities.Order", "OrderCodeNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderCode")
                        .HasConstraintName("FK__OrderDeta__Order__66603565");

                    b.HasOne("ASMS.Repositories.Entities.Room", "RoomCodeNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("RoomCode")
                        .HasConstraintName("FK__OrderDeta__RoomC__6754599E");

                    b.HasOne("ASMS.Repositories.Entities.Service", "Service")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__OrderDeta__Servi__693CA210");

                    b.Navigation("BoxCodeNavigation");

                    b.Navigation("OrderCodeNavigation");

                    b.Navigation("RoomCodeNavigation");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.PaymentHistory", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Order", "OrderCodeNavigation")
                        .WithMany("PaymentHistories")
                        .HasForeignKey("OrderCode")
                        .HasConstraintName("FK__PaymentHi__Order__74AE54BC");

                    b.Navigation("OrderCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Room", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Floor", "FloorCodeNavigation")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorCode")
                        .HasConstraintName("FK__Room__FloorCode__5629CD9C");

                    b.HasOne("ASMS.Repositories.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .HasConstraintName("FK__Room__RoomTypeID__571DF1D5");

                    b.Navigation("FloorCodeNavigation");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.TrackingHistory", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Order", "OrderCodeNavigation")
                        .WithMany("TrackingHistories")
                        .HasForeignKey("OrderCode")
                        .HasConstraintName("FK__TrackingH__Order__6C190EBB");

                    b.Navigation("OrderCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowStep", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("WorkflowTemplateId")
                        .HasConstraintName("FK__WorkflowS__Workf__4E88ABD4");

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowTemplate", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.RoomType", "RoomType")
                        .WithMany("WorkflowTemplates")
                        .HasForeignKey("RoomTypeId")
                        .HasConstraintName("FK__WorkflowT__RoomT__4BAC3F29");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Box", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Building", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Floors");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Cell", b =>
                {
                    b.Navigation("Boxes");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.EmployeeRole", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("PaymentHistories");

                    b.Navigation("TrackingHistories");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Room", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.RoomType", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("WorkflowTemplates");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Service", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowTemplate", b =>
                {
                    b.Navigation("WorkflowSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
