// <auto-generated />
using System;
using ASMS.Repositories.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASMS.Repositories.Migrations
{
    [DbContext(typeof(VstorageContext))]
    [Migration("20251125142105_InitialCreateDb1")]
    partial class InitialCreateDb1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASMS.Repositories.Entities.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Area")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BuildingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("BuildingId");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Container", b =>
                {
                    b.Property<string>("ContainerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContainerAboveCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ContainerTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("FloorCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<DateTime?>("LastOptimizedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Layer")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(100m);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("OptimizationScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("OrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailID");

                    b.Property<decimal?>("PositionX")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("PositionY")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("PositionZ")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductTypeID");

                    b.Property<int?>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ContainerCode")
                        .HasName("PK__Containe__874FE471B6792E9D");

                    b.HasIndex("ContainerTypeId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex(new[] { "FloorCode" }, "IX_Container_FloorCode");

                    b.ToTable("Container", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ContainerLocationLog", b =>
                {
                    b.Property<int>("ContainerLocationLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ContainerLocationLogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContainerLocationLogId"));

                    b.Property<string>("Algorithm")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContainerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CurrentFloor")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldFloor")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("UpdatedDate")
                        .HasColumnType("date");

                    b.HasKey("ContainerLocationLogId")
                        .HasName("PK__Containe__06E7FAAA2A79C5C0");

                    b.HasIndex(new[] { "ContainerCode" }, "IX_ContainerLocationLog_ContainerCode");

                    b.HasIndex(new[] { "ContainerCode", "UpdatedDate" }, "IX_ContainerLocationLog_Container_Date");

                    b.HasIndex(new[] { "OrderCode" }, "IX_ContainerLocationLog_Order");

                    b.ToTable("ContainerLocationLog", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ContainerType", b =>
                {
                    b.Property<int>("ContainerTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContainerTypeId"));

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ContainerTypeId")
                        .HasName("PK__Containe__46FA6FD9D2C4FA11");

                    b.ToTable("ContainerType", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CustomerCode" }, "UQ_Customer_CustomerCode")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("EmployeeRoleId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeRoleID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Employee__1F642549B4A50CB4");

                    b.HasIndex(new[] { "BuildingId" }, "IX_Employees_BuildingId");

                    b.HasIndex(new[] { "EmployeeRoleId" }, "IX_Employees_EmployeeRoleID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeRoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeRoleId"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("EmployeeRoleId")
                        .HasName("PK__Employee__3461868636646C5A");

                    b.ToTable("EmployeeRole", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Floor", b =>
                {
                    b.Property<string>("FloorCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("CurrentContainerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("CurrentWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("MaxContainers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20);

                    b.Property<decimal?>("MaxWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(500m);

                    b.Property<string>("ShelfCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("UtilizationRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("FloorCode")
                        .HasName("PK__Floor__394E956B81A832F4");

                    b.HasIndex(new[] { "ShelfCode" }, "IX_Floor_ShelfCode");

                    b.ToTable("Floor", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Order", b =>
                {
                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("DepositDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PhoneContact")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<int?>("ShelfQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("ShelfTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("StorageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("StorageTypeID");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("UnpaidAmount")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("OrderCode")
                        .HasName("PK__Order__999B52287CF5E3A0");

                    b.HasIndex(new[] { "CustomerCode" }, "IX_Order_CustomerCode");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailID");

                    b.Property<string>("ContainerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ContainerQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("ContainerType")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Quantity")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StorageCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__OrderDet__D3B9D30C9215E8D7");

                    b.HasIndex(new[] { "ContainerCode" }, "IX_OrderDetail_ContainerCode");

                    b.HasIndex(new[] { "OrderCode" }, "IX_OrderDetail_OrderCode");

                    b.HasIndex(new[] { "StorageCode" }, "IX_OrderDetail_StorageCode");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.OrderDetailProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__OrderDet__3214EC07CB864502");

                    b.HasIndex(new[] { "OrderDetailId" }, "IX_OrderDetailProductType_OrderDetailId");

                    b.HasIndex(new[] { "ProductTypeId" }, "IX_OrderDetailProductType_ProductTypeId");

                    b.HasIndex(new[] { "OrderDetailId", "ProductTypeId" }, "UQ_OrderDetailProductType_OrderDetail_ProductType")
                        .IsUnique();

                    b.ToTable("OrderDetailProductType", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.OrderDetailService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__OrderDet__3214EC07CD915A73");

                    b.HasIndex("ServiceId");

                    b.HasIndex(new[] { "OrderDetailId", "ServiceId" }, "UQ_OrderDetailService_OrderDetail_Service")
                        .IsUnique();

                    b.ToTable("OrderDetailService", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.PaymentHistory", b =>
                {
                    b.Property<string>("PaymentHistoryCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentPlatform")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PaymentHistoryCode")
                        .HasName("PK__PaymentH__F83BEDA4194B7DFF");

                    b.HasIndex("OrderCode");

                    b.ToTable("PaymentHistory", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.PaymentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode");

                    b.ToTable("PaymentResult", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ProductType", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductTypeId"));

                    b.Property<bool?>("CanStack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<bool?>("IsFragile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ProductTypeId")
                        .HasName("PK__ProductT__A1312F4E69BB1C0D");

                    b.ToTable("ProductType", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("ServiceId")
                        .HasName("PK__Service__C51BB0EA2D1E364C");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Shelf", b =>
                {
                    b.Property<string>("ShelfCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("ShelfTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("StorageCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ShelfCode")
                        .HasName("PK__Shelf__24D15D7509E5371F");

                    b.HasIndex("ShelfTypeId");

                    b.HasIndex(new[] { "StorageCode" }, "IX_Shelf_StorageCode");

                    b.ToTable("Shelf", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ShelfType", b =>
                {
                    b.Property<int>("ShelfTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShelfTypeId"));

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ShelfTypeId")
                        .HasName("PK__ShelfTyp__50AF6654E81B2766");

                    b.ToTable("ShelfType", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Storage", b =>
                {
                    b.Property<string>("StorageCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BuildingCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<DateTime?>("LastOptimizedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("OccupiedContainers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductTypeID");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("StorageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("StorageTypeID");

                    b.Property<int?>("TotalContainers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("TotalVolume")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(32, 6)")
                        .HasComputedColumnSql("(([Length]*[Width])*[Height])", false);

                    b.Property<decimal?>("UsedVolume")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("UtilizationRate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(38, 15)")
                        .HasComputedColumnSql("(case when ([Length]*[Width])*[Height]>(0) then ([UsedVolume]/(([Length]*[Width])*[Height]))*(100) else (0) end)", false);

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("StorageCode")
                        .HasName("PK__Storage__AD8F8BC7D5ABE087");

                    b.HasIndex(new[] { "BuildingId" }, "IX_Storage_BuildingId");

                    b.HasIndex(new[] { "ProductTypeId" }, "IX_Storage_ProductTypeID");

                    b.HasIndex(new[] { "StorageTypeId" }, "IX_Storage_StorageTypeID");

                    b.ToTable("Storage", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.StorageType", b =>
                {
                    b.Property<int>("StorageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("StorageTypeID");

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("TotalVolume")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("StorageTypeId")
                        .HasName("PK__StorageT__C94B8F7DD4F87BA1");

                    b.ToTable("StorageType", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.TrackingHistory", b =>
                {
                    b.Property<int>("TrackingHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TrackingHistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackingHistoryId"));

                    b.Property<string>("ActionType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly?>("CreateAt")
                        .HasColumnType("date");

                    b.Property<string>("CurrentAssign")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NextAssign")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OrderDetailCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TrackingHistoryId")
                        .HasName("PK__Tracking__26DB07A738199CF4");

                    b.HasIndex(new[] { "OrderCode" }, "IX_TrackingHistory_OrderCode");

                    b.ToTable("TrackingHistory", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowStep", b =>
                {
                    b.Property<int>("WorkflowStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WorkflowStepID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkflowStepId"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("StepNumber")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowTemplateID");

                    b.HasKey("WorkflowStepId")
                        .HasName("PK__Workflow__36121401BCF42ECF");

                    b.HasIndex(new[] { "WorkflowTemplateId" }, "IX_WorkflowStep_WorkflowTemplateID");

                    b.ToTable("WorkflowStep", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowTemplate", b =>
                {
                    b.Property<int>("WorkflowTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowTemplateID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("WorkflowTemplateId")
                        .HasName("PK__Workflow__96E60A37BE8B1C29");

                    b.ToTable("WorkflowTemplate", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Container", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.ContainerType", "ContainerType")
                        .WithMany("Containers")
                        .HasForeignKey("ContainerTypeId")
                        .HasConstraintName("FK_Container_ContainerType");

                    b.HasOne("ASMS.Repositories.Entities.Floor", "FloorCodeNavigation")
                        .WithMany("Containers")
                        .HasForeignKey("FloorCode")
                        .HasConstraintName("FK__Container__Floor__656C112C");

                    b.HasOne("ASMS.Repositories.Entities.ProductType", "ProductType")
                        .WithMany("Containers")
                        .HasForeignKey("ProductTypeId")
                        .HasConstraintName("FK_Container_ProductType");

                    b.Navigation("ContainerType");

                    b.Navigation("FloorCodeNavigation");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ContainerLocationLog", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Container", "ContainerCodeNavigation")
                        .WithMany("ContainerLocationLogs")
                        .HasForeignKey("ContainerCode")
                        .HasConstraintName("FK__Container__Conta__68487DD7");

                    b.Navigation("ContainerCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Employee", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Building", "Building")
                        .WithMany("Employees")
                        .HasForeignKey("BuildingId")
                        .HasConstraintName("FK__Employee__Buildi__7D439ABD");

                    b.HasOne("ASMS.Repositories.Entities.EmployeeRole", "EmployeeRole")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeRoleId")
                        .HasConstraintName("FK__Employee__Employ__7C4F7684");

                    b.Navigation("Building");

                    b.Navigation("EmployeeRole");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Floor", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Shelf", "ShelfCodeNavigation")
                        .WithMany("Floors")
                        .HasForeignKey("ShelfCode")
                        .HasConstraintName("FK__Floor__ShelfCode__5FB337D6");

                    b.Navigation("ShelfCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Order", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Customer", "CustomerCodeNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerCode")
                        .HasPrincipalKey("CustomerCode")
                        .HasConstraintName("FK_Order_CustomerCode");

                    b.Navigation("CustomerCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.OrderDetail", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Container", "ContainerCodeNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ContainerCode")
                        .HasConstraintName("FK__OrderDeta__Conta__73BA3083");

                    b.HasOne("ASMS.Repositories.Entities.Order", "OrderCodeNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderCode")
                        .HasConstraintName("FK__OrderDeta__Order__71D1E811");

                    b.HasOne("ASMS.Repositories.Entities.Storage", "StorageCodeNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("StorageCode")
                        .HasConstraintName("FK__OrderDeta__Stora__72C60C4A");

                    b.Navigation("ContainerCodeNavigation");

                    b.Navigation("OrderCodeNavigation");

                    b.Navigation("StorageCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.OrderDetailProductType", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.OrderDetail", "OrderDetail")
                        .WithMany("OrderDetailProductTypes")
                        .HasForeignKey("OrderDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetailProductType_OrderDetail");

                    b.HasOne("ASMS.Repositories.Entities.ProductType", "ProductType")
                        .WithMany("OrderDetailProductTypes")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetailProductType_ProductType");

                    b.Navigation("OrderDetail");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.OrderDetailService", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.OrderDetail", "OrderDetail")
                        .WithMany("OrderDetailServices")
                        .HasForeignKey("OrderDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetailService_OrderDetail");

                    b.HasOne("ASMS.Repositories.Entities.Service", "Service")
                        .WithMany("OrderDetailServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetailService_Service");

                    b.Navigation("OrderDetail");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.PaymentHistory", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Order", "OrderCodeNavigation")
                        .WithMany("PaymentHistories")
                        .HasForeignKey("OrderCode")
                        .HasConstraintName("FK__PaymentHi__Order__29221CFB");

                    b.Navigation("OrderCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.PaymentResult", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Order", "Order")
                        .WithMany("PaymentResults")
                        .HasForeignKey("OrderCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.RefreshToken", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Customer", "Customer")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ASMS.Repositories.Entities.Employee", "Employee")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Shelf", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.ShelfType", "ShelfType")
                        .WithMany("Shelves")
                        .HasForeignKey("ShelfTypeId")
                        .HasConstraintName("FK_Shelf_ShelfType");

                    b.HasOne("ASMS.Repositories.Entities.Storage", "StorageCodeNavigation")
                        .WithMany("Shelves")
                        .HasForeignKey("StorageCode")
                        .HasConstraintName("FK__Shelf__StorageCo__5CD6CB2B");

                    b.Navigation("ShelfType");

                    b.Navigation("StorageCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Storage", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Building", "Building")
                        .WithMany("Storages")
                        .HasForeignKey("BuildingId")
                        .HasConstraintName("FK__Storage__Buildin__5535A963");

                    b.HasOne("ASMS.Repositories.Entities.ProductType", "ProductType")
                        .WithMany("Storages")
                        .HasForeignKey("ProductTypeId")
                        .HasConstraintName("FK__Storage__Product__571DF1D5");

                    b.HasOne("ASMS.Repositories.Entities.StorageType", "StorageType")
                        .WithMany("Storages")
                        .HasForeignKey("StorageTypeId")
                        .HasConstraintName("FK__Storage__Storage__5629CD9C");

                    b.Navigation("Building");

                    b.Navigation("ProductType");

                    b.Navigation("StorageType");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.TrackingHistory", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Order", "OrderCodeNavigation")
                        .WithMany("TrackingHistories")
                        .HasForeignKey("OrderCode")
                        .HasConstraintName("FK__TrackingH__Order__778AC167");

                    b.Navigation("OrderCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowStep", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("WorkflowTemplateId")
                        .HasConstraintName("FK__WorkflowS__Workf__4E88ABD4");

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Building", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Storages");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Container", b =>
                {
                    b.Navigation("ContainerLocationLogs");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ContainerType", b =>
                {
                    b.Navigation("Containers");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Employee", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.EmployeeRole", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Floor", b =>
                {
                    b.Navigation("Containers");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("PaymentHistories");

                    b.Navigation("PaymentResults");

                    b.Navigation("TrackingHistories");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.OrderDetail", b =>
                {
                    b.Navigation("OrderDetailProductTypes");

                    b.Navigation("OrderDetailServices");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ProductType", b =>
                {
                    b.Navigation("Containers");

                    b.Navigation("OrderDetailProductTypes");

                    b.Navigation("Storages");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Service", b =>
                {
                    b.Navigation("OrderDetailServices");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Shelf", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ShelfType", b =>
                {
                    b.Navigation("Shelves");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Storage", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Shelves");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.StorageType", b =>
                {
                    b.Navigation("Storages");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowTemplate", b =>
                {
                    b.Navigation("WorkflowSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
