// <auto-generated />
using System;
using ASMS.Repositories.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASMS.Repositories.Migrations
{
    [DbContext(typeof(VstorageContext))]
    [Migration("20251102170010_FixPendingModelChanges")]
    partial class FixPendingModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASMS.Repositories.Entities.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Area")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BuildingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("FloorQuantity")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("BuildingId");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Container", b =>
                {
                    b.Property<string>("ContainerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("CurrentItemCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("CurrentWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("FloorCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("HasFragileItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("HasHeavyItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<DateTime?>("LastOptimizedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("MaxItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50);

                    b.Property<decimal?>("MaxWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(100m);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("OptimizationScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("PositionX")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("PositionY")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("PositionZ")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductTypeID");

                    b.Property<int?>("RotationAngle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("TotalVolume")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(38, 0)")
                        .HasComputedColumnSql("(([Length]*[Width])*[Height])", true);

                    b.Property<decimal?>("UsedVolume")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("UtilizationRate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(38, 21)")
                        .HasComputedColumnSql("(case when ([Length]*[Width])*[Height]>(0) then ([UsedVolume]/(([Length]*[Width])*[Height]))*(100) else (0) end)", true);

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("ContainerCode")
                        .HasName("PK__Containe__874FE471B6792E9D");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex(new[] { "FloorCode" }, "IX_Container_FloorCode");

                    b.ToTable("Container", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ContainerLocationLog", b =>
                {
                    b.Property<int>("ContainerLocationLogId")
                        .HasColumnType("int")
                        .HasColumnName("ContainerLocationLogID");

                    b.Property<string>("Algorithm")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContainerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CurrentFloor")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldFloor")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("UpdatedDate")
                        .HasColumnType("date");

                    b.HasKey("ContainerLocationLogId")
                        .HasName("PK__Containe__06E7FAAA2A79C5C0");

                    b.HasIndex(new[] { "ContainerCode" }, "IX_ContainerLocationLog_ContainerCode");

                    b.HasIndex(new[] { "ContainerCode", "UpdatedDate" }, "IX_ContainerLocationLog_Container_Date");

                    b.HasIndex(new[] { "OrderCode" }, "IX_ContainerLocationLog_Order");

                    b.ToTable("ContainerLocationLog", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CustomerCode" }, "AK_Customer_CustomerCode")
                        .IsUnique();

                    b.HasIndex(new[] { "CustomerCode" }, "UQ_Customer_CustomerCode")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("EmployeeRoleId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeRoleID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Employee__1F642549B4A50CB4");

                    b.HasIndex(new[] { "BuildingId" }, "IX_Employees_BuildingId");

                    b.HasIndex(new[] { "EmployeeRoleId" }, "IX_Employees_EmployeeRoleID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeRoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeRoleId"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("EmployeeRoleId")
                        .HasName("PK__Employee__3461868636646C5A");

                    b.ToTable("EmployeeRole", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Floor", b =>
                {
                    b.Property<string>("FloorCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("CurrentContainerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("CurrentWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("MaxContainers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20);

                    b.Property<decimal?>("MaxWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(500m);

                    b.Property<decimal?>("PositionX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("PositionY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("PositionZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ShelfCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("UtilizationRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("FloorCode")
                        .HasName("PK__Floor__394E956B81A832F4");

                    b.HasIndex(new[] { "ShelfCode" }, "IX_Floor_ShelfCode");

                    b.ToTable("Floor", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.FloorBlock", b =>
                {
                    b.Property<string>("FloorBlockCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FloorCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("FloorBlockCode")
                        .HasName("PK__FloorBlo__DF861D583ABE3DA3");

                    b.HasIndex(new[] { "FloorCode" }, "IX_FloorBlock_FloorCode");

                    b.ToTable("FloorBlock", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("AccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("CanStack")
                        .HasColumnType("bit");

                    b.Property<string>("ContainerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("FrequencyUse")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Low");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ImageURL");

                    b.Property<bool?>("IsFragile")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAccessDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailID");

                    b.Property<decimal?>("PlacementScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("PositionX")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("PositionY")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("PositionZ")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductTypeID");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("RotationAngle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Volume")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(32, 6)")
                        .HasComputedColumnSql("(([Length]*[Width])*[Height])", true);

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ItemId")
                        .HasName("PK__Item__727E83EB9C3E14D6");

                    b.HasIndex("ContainerCode");

                    b.HasIndex("OrderDetailId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Order", b =>
                {
                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("DepositDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("UnpaidAmount")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("OrderCode")
                        .HasName("PK__Order__999B52287CF5E3A0");

                    b.HasIndex(new[] { "CustomerCode" }, "IX_Order_CustomerCode");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailID");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContainerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Quantity")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<string>("StorageCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__OrderDet__D3B9D30C9215E8D7");

                    b.HasIndex(new[] { "ContainerCode" }, "IX_OrderDetail_ContainerCode");

                    b.HasIndex(new[] { "OrderCode" }, "IX_OrderDetail_OrderCode");

                    b.HasIndex(new[] { "ServiceId" }, "IX_OrderDetail_ServiceID");

                    b.HasIndex(new[] { "StorageCode" }, "IX_OrderDetail_StorageCode");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.PaymentHistory", b =>
                {
                    b.Property<string>("PaymentHistoryCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentPlatform")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PaymentHistoryCode")
                        .HasName("PK__PaymentH__F83BEDA4194B7DFF");

                    b.HasIndex("OrderCode");

                    b.ToTable("PaymentHistory", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ProductType", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductTypeId"));

                    b.Property<decimal?>("AverageWeight")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool?>("AvoidSunlight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("CanStack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<bool?>("IsFragile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MaxStackLayers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("PlacementPriority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("PreferredZone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("RequireMoistureControl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("RequireVentilation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ShapeType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ProductTypeId")
                        .HasName("PK__ProductT__A1312F4E69BB1C0D");

                    b.ToTable("ProductType", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("ServiceId")
                        .HasName("PK__Service__C51BB0EA2D1E364C");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Shelf", b =>
                {
                    b.Property<string>("ShelfCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("StorageCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("ShelfCode")
                        .HasName("PK__Shelf__24D15D7509E5371F");

                    b.HasIndex(new[] { "StorageCode" }, "IX_Shelf_StorageCode");

                    b.ToTable("Shelf", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Storage", b =>
                {
                    b.Property<string>("StorageCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<DateTime?>("LastOptimizedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("OccupiedContainers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductTypeID");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("StorageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("StorageTypeID");

                    b.Property<int?>("TotalContainers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("TotalVolume")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(38, 0)")
                        .HasComputedColumnSql("(([Length]*[Width])*[Height])", true);

                    b.Property<decimal?>("UsedVolume")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("UtilizationRate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(38, 21)")
                        .HasComputedColumnSql("(case when ([Length]*[Width])*[Height]>(0) then ([UsedVolume]/(([Length]*[Width])*[Height]))*(100) else (0) end)", true);

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("StorageCode")
                        .HasName("PK__Storage__AD8F8BC7D5ABE087");

                    b.HasIndex(new[] { "BuildingId" }, "IX_Storage_BuildingId");

                    b.HasIndex(new[] { "ProductTypeId" }, "IX_Storage_ProductTypeID");

                    b.HasIndex(new[] { "StorageTypeId" }, "IX_Storage_StorageTypeID");

                    b.ToTable("Storage", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.StorageBlock", b =>
                {
                    b.Property<string>("StorageBlockCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("StorageCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("StorageBlockCode")
                        .HasName("PK__StorageB__10B0C0AD25AD5F9E");

                    b.HasIndex(new[] { "StorageCode" }, "IX_StorageBlock_StorageCode");

                    b.ToTable("StorageBlock", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.StorageType", b =>
                {
                    b.Property<int>("StorageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("StorageTypeID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StorageTypeId")
                        .HasName("PK__StorageT__C94B8F7DD4F87BA1");

                    b.ToTable("StorageType", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.TrackingHistory", b =>
                {
                    b.Property<int>("TrackingHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TrackingHistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackingHistoryId"));

                    b.Property<string>("ActionType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly?>("CreateAt")
                        .HasColumnType("date");

                    b.Property<string>("CurrentAssign")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NextAssign")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OrderDetailCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TrackingHistoryId")
                        .HasName("PK__Tracking__26DB07A738199CF4");

                    b.HasIndex(new[] { "OrderCode" }, "IX_TrackingHistory_OrderCode");

                    b.ToTable("TrackingHistory", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowStep", b =>
                {
                    b.Property<int>("WorkflowStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WorkflowStepID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkflowStepId"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("StepNumber")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowTemplateID");

                    b.HasKey("WorkflowStepId")
                        .HasName("PK__Workflow__36121401BCF42ECF");

                    b.HasIndex(new[] { "WorkflowTemplateId" }, "IX_WorkflowStep_WorkflowTemplateID");

                    b.ToTable("WorkflowStep", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowTemplate", b =>
                {
                    b.Property<int>("WorkflowTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowTemplateID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("StorageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("StorageTypeID");

                    b.HasKey("WorkflowTemplateId")
                        .HasName("PK__Workflow__96E60A37BE8B1C29");

                    b.HasIndex(new[] { "StorageTypeId" }, "IX_WorkflowTemplate_StorageTypeID");

                    b.ToTable("WorkflowTemplate", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Container", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Floor", "FloorCodeNavigation")
                        .WithMany("Containers")
                        .HasForeignKey("FloorCode")
                        .HasConstraintName("FK__Container__Floor__656C112C");

                    b.HasOne("ASMS.Repositories.Entities.ProductType", "ProductType")
                        .WithMany("Containers")
                        .HasForeignKey("ProductTypeId")
                        .HasConstraintName("FK_Container_ProductType");

                    b.Navigation("FloorCodeNavigation");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ContainerLocationLog", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Container", "ContainerCodeNavigation")
                        .WithMany("ContainerLocationLogs")
                        .HasForeignKey("ContainerCode")
                        .HasConstraintName("FK__Container__Conta__68487DD7");

                    b.Navigation("ContainerCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Employee", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Building", "Building")
                        .WithMany("Employees")
                        .HasForeignKey("BuildingId")
                        .HasConstraintName("FK__Employee__Buildi__7D439ABD");

                    b.HasOne("ASMS.Repositories.Entities.EmployeeRole", "EmployeeRole")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeRoleId")
                        .HasConstraintName("FK__Employee__Employ__7C4F7684");

                    b.Navigation("Building");

                    b.Navigation("EmployeeRole");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Floor", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Shelf", "ShelfCodeNavigation")
                        .WithMany("Floors")
                        .HasForeignKey("ShelfCode")
                        .HasConstraintName("FK__Floor__ShelfCode__5FB337D6");

                    b.Navigation("ShelfCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.FloorBlock", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Floor", "FloorCodeNavigation")
                        .WithMany("FloorBlocks")
                        .HasForeignKey("FloorCode")
                        .HasConstraintName("FK__FloorBloc__Floor__160F4887");

                    b.Navigation("FloorCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Item", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Container", "ContainerCodeNavigation")
                        .WithMany("Items")
                        .HasForeignKey("ContainerCode")
                        .HasConstraintName("FK__Item__ContainerC__3A4CA8FD");

                    b.HasOne("ASMS.Repositories.Entities.OrderDetail", "OrderDetail")
                        .WithMany("Items")
                        .HasForeignKey("OrderDetailId")
                        .IsRequired()
                        .HasConstraintName("FK__Item__OrderDetai__395884C4");

                    b.HasOne("ASMS.Repositories.Entities.ProductType", "ProductType")
                        .WithMany("Items")
                        .HasForeignKey("ProductTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Item__ProductTyp__3B40CD36");

                    b.Navigation("ContainerCodeNavigation");

                    b.Navigation("OrderDetail");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Order", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Customer", "CustomerCodeNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerCode")
                        .HasPrincipalKey("CustomerCode")
                        .HasConstraintName("FK_Order_CustomerCode");

                    b.Navigation("CustomerCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.OrderDetail", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Container", "ContainerCodeNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ContainerCode")
                        .HasConstraintName("FK__OrderDeta__Conta__73BA3083");

                    b.HasOne("ASMS.Repositories.Entities.Order", "OrderCodeNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderCode")
                        .HasConstraintName("FK__OrderDeta__Order__71D1E811");

                    b.HasOne("ASMS.Repositories.Entities.Service", "Service")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__OrderDeta__Servi__74AE54BC");

                    b.HasOne("ASMS.Repositories.Entities.Storage", "StorageCodeNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("StorageCode")
                        .HasConstraintName("FK__OrderDeta__Stora__72C60C4A");

                    b.Navigation("ContainerCodeNavigation");

                    b.Navigation("OrderCodeNavigation");

                    b.Navigation("Service");

                    b.Navigation("StorageCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.PaymentHistory", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Order", "OrderCodeNavigation")
                        .WithMany("PaymentHistories")
                        .HasForeignKey("OrderCode")
                        .HasConstraintName("FK__PaymentHi__Order__29221CFB");

                    b.Navigation("OrderCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Shelf", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Storage", "StorageCodeNavigation")
                        .WithMany("Shelves")
                        .HasForeignKey("StorageCode")
                        .HasConstraintName("FK__Shelf__StorageCo__5CD6CB2B");

                    b.Navigation("StorageCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Storage", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Building", "Building")
                        .WithMany("Storages")
                        .HasForeignKey("BuildingId")
                        .HasConstraintName("FK__Storage__Buildin__5535A963");

                    b.HasOne("ASMS.Repositories.Entities.ProductType", "ProductType")
                        .WithMany("Storages")
                        .HasForeignKey("ProductTypeId")
                        .HasConstraintName("FK__Storage__Product__571DF1D5");

                    b.HasOne("ASMS.Repositories.Entities.StorageType", "StorageType")
                        .WithMany("Storages")
                        .HasForeignKey("StorageTypeId")
                        .HasConstraintName("FK__Storage__Storage__5629CD9C");

                    b.Navigation("Building");

                    b.Navigation("ProductType");

                    b.Navigation("StorageType");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.StorageBlock", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Storage", "StorageCodeNavigation")
                        .WithMany("StorageBlocks")
                        .HasForeignKey("StorageCode")
                        .HasConstraintName("FK__StorageBl__Stora__59FA5E80");

                    b.Navigation("StorageCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.TrackingHistory", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Order", "OrderCodeNavigation")
                        .WithMany("TrackingHistories")
                        .HasForeignKey("OrderCode")
                        .HasConstraintName("FK__TrackingH__Order__778AC167");

                    b.Navigation("OrderCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowStep", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("WorkflowTemplateId")
                        .HasConstraintName("FK__WorkflowS__Workf__4E88ABD4");

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowTemplate", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.StorageType", "StorageType")
                        .WithMany("WorkflowTemplates")
                        .HasForeignKey("StorageTypeId")
                        .HasConstraintName("FK__WorkflowT__Stora__4BAC3F29");

                    b.Navigation("StorageType");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Building", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Storages");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Container", b =>
                {
                    b.Navigation("ContainerLocationLogs");

                    b.Navigation("Items");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.EmployeeRole", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Floor", b =>
                {
                    b.Navigation("Containers");

                    b.Navigation("FloorBlocks");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("PaymentHistories");

                    b.Navigation("TrackingHistories");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.OrderDetail", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ProductType", b =>
                {
                    b.Navigation("Containers");

                    b.Navigation("Items");

                    b.Navigation("Storages");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Service", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Shelf", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Storage", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Shelves");

                    b.Navigation("StorageBlocks");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.StorageType", b =>
                {
                    b.Navigation("Storages");

                    b.Navigation("WorkflowTemplates");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowTemplate", b =>
                {
                    b.Navigation("WorkflowSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
