// <auto-generated />
using System;
using ASMS.Repositories.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASMS.Repositories.Migrations
{
    [DbContext(typeof(VstorageContext))]
    [Migration("20251008151858_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASMS.Repositories.Entities.Building", b =>
                {
                    b.Property<string>("BuildingCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Area")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("FloorQuantity")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("BuildingCode")
                        .HasName("PK__Building__D4DA0325D3A2B9AB");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Container", b =>
                {
                    b.Property<string>("ContainerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FloorCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("ContainerCode")
                        .HasName("PK__Containe__874FE471B6792E9D");

                    b.HasIndex("FloorCode");

                    b.ToTable("Container", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ContainerLocationLog", b =>
                {
                    b.Property<int>("ContainerLocationLogId")
                        .HasColumnType("int")
                        .HasColumnName("ContainerLocationLogID");

                    b.Property<string>("Assign")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContainerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CurrentFloor")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OldFloor")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("UpdatedDate")
                        .HasColumnType("date");

                    b.HasKey("ContainerLocationLogId")
                        .HasName("PK__Containe__06E7FAAA2A79C5C0");

                    b.HasIndex("ContainerCode");

                    b.ToTable("ContainerLocationLog", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ContainerType", b =>
                {
                    b.Property<int>("ContainerTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ContainerTypeID");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductTypeID");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("ContainerTypeId")
                        .HasName("PK__Containe__46FA6FF98608AE3E");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("ContainerType", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Customer", b =>
                {
                    b.Property<string>("CustomerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CustomerCode")
                        .HasName("PK__Customer__066785204D979A27");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Employee", b =>
                {
                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BuildingCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("EmployeeRoleId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeRoleID");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("EmployeeCode")
                        .HasName("PK__Employee__1F642549B4A50CB4");

                    b.HasIndex("BuildingCode");

                    b.HasIndex("EmployeeRoleId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeRoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeRoleId"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("EmployeeRoleId")
                        .HasName("PK__Employee__3461868636646C5A");

                    b.ToTable("EmployeeRole", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Floor", b =>
                {
                    b.Property<string>("FloorCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("ShelfCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("FloorCode")
                        .HasName("PK__Floor__394E956B81A832F4");

                    b.HasIndex("ShelfCode");

                    b.ToTable("Floor", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.FloorBlock", b =>
                {
                    b.Property<string>("FloorBlockCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FloorCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("FloorBlockCode")
                        .HasName("PK__FloorBlo__DF861D583ABE3DA3");

                    b.HasIndex("FloorCode");

                    b.ToTable("FloorBlock", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Order", b =>
                {
                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("DepositDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("UnpaidAmount")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("OrderCode")
                        .HasName("PK__Order__999B52287CF5E3A0");

                    b.HasIndex("CustomerCode");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailID");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContainerCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Quantity")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<string>("StorageCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__OrderDet__D3B9D30C9215E8D7");

                    b.HasIndex("ContainerCode");

                    b.HasIndex("OrderCode");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StorageCode");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ProductType", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductTypeID");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ProductTypeId")
                        .HasName("PK__ProductT__A1312F4E69BB1C0D");

                    b.ToTable("ProductType", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("ServiceId")
                        .HasName("PK__Service__C51BB0EA2D1E364C");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Shelf", b =>
                {
                    b.Property<string>("ShelfCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("StorageCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("ShelfCode")
                        .HasName("PK__Shelf__24D15D7509E5371F");

                    b.HasIndex("StorageCode");

                    b.ToTable("Shelf", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Storage", b =>
                {
                    b.Property<string>("StorageCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BuildingCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ProductTypeID");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("StorageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("StorageTypeID");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("StorageCode")
                        .HasName("PK__Storage__AD8F8BC7D5ABE087");

                    b.HasIndex("BuildingCode");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("StorageTypeId");

                    b.ToTable("Storage", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.StorageBlock", b =>
                {
                    b.Property<string>("StorageBlockCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("StorageCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("StorageBlockCode")
                        .HasName("PK__StorageB__10B0C0AD25AD5F9E");

                    b.HasIndex("StorageCode");

                    b.ToTable("StorageBlock", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.StorageType", b =>
                {
                    b.Property<int>("StorageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("StorageTypeID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StorageTypeId")
                        .HasName("PK__StorageT__C94B8F7DD4F87BA1");

                    b.ToTable("StorageType", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.TrackingHistory", b =>
                {
                    b.Property<int>("TrackingHistoryId")
                        .HasColumnType("int")
                        .HasColumnName("TrackingHistoryID");

                    b.Property<string>("ActionType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly?>("CreateAt")
                        .HasColumnType("date");

                    b.Property<string>("CurrentAssign")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NextAssign")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OrderDetailCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TrackingHistoryId")
                        .HasName("PK__Tracking__26DB07A738199CF4");

                    b.HasIndex("OrderCode");

                    b.ToTable("TrackingHistory", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowStep", b =>
                {
                    b.Property<int>("WorkflowStepId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowStepID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("StepNumber")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowTemplateID");

                    b.HasKey("WorkflowStepId")
                        .HasName("PK__Workflow__36121401BCF42ECF");

                    b.HasIndex("WorkflowTemplateId");

                    b.ToTable("WorkflowStep", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowTemplate", b =>
                {
                    b.Property<int>("WorkflowTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowTemplateID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("StorageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("StorageTypeID");

                    b.HasKey("WorkflowTemplateId")
                        .HasName("PK__Workflow__96E60A37BE8B1C29");

                    b.HasIndex("StorageTypeId");

                    b.ToTable("WorkflowTemplate", (string)null);
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Container", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Floor", "FloorCodeNavigation")
                        .WithMany("Containers")
                        .HasForeignKey("FloorCode")
                        .HasConstraintName("FK__Container__Floor__656C112C");

                    b.Navigation("FloorCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ContainerLocationLog", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Container", "ContainerCodeNavigation")
                        .WithMany("ContainerLocationLogs")
                        .HasForeignKey("ContainerCode")
                        .HasConstraintName("FK__Container__Conta__68487DD7");

                    b.Navigation("ContainerCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ContainerType", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.ProductType", "ProductType")
                        .WithMany("ContainerTypes")
                        .HasForeignKey("ProductTypeId")
                        .HasConstraintName("FK__Container__Produ__628FA481");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Employee", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Building", "BuildingCodeNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("BuildingCode")
                        .HasConstraintName("FK__Employee__Buildi__7D439ABD");

                    b.HasOne("ASMS.Repositories.Entities.EmployeeRole", "EmployeeRole")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeRoleId")
                        .HasConstraintName("FK__Employee__Employ__7C4F7684");

                    b.Navigation("BuildingCodeNavigation");

                    b.Navigation("EmployeeRole");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Floor", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Shelf", "ShelfCodeNavigation")
                        .WithMany("Floors")
                        .HasForeignKey("ShelfCode")
                        .HasConstraintName("FK__Floor__ShelfCode__5FB337D6");

                    b.Navigation("ShelfCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.FloorBlock", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Floor", "FloorCodeNavigation")
                        .WithMany("FloorBlocks")
                        .HasForeignKey("FloorCode")
                        .HasConstraintName("FK__FloorBloc__Floor__160F4887");

                    b.Navigation("FloorCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Order", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Customer", "CustomerCodeNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerCode")
                        .HasConstraintName("FK__Order__CustomerC__6EF57B66");

                    b.Navigation("CustomerCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.OrderDetail", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Container", "ContainerCodeNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ContainerCode")
                        .HasConstraintName("FK__OrderDeta__Conta__73BA3083");

                    b.HasOne("ASMS.Repositories.Entities.Order", "OrderCodeNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderCode")
                        .HasConstraintName("FK__OrderDeta__Order__71D1E811");

                    b.HasOne("ASMS.Repositories.Entities.Service", "Service")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__OrderDeta__Servi__74AE54BC");

                    b.HasOne("ASMS.Repositories.Entities.Storage", "StorageCodeNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("StorageCode")
                        .HasConstraintName("FK__OrderDeta__Stora__72C60C4A");

                    b.Navigation("ContainerCodeNavigation");

                    b.Navigation("OrderCodeNavigation");

                    b.Navigation("Service");

                    b.Navigation("StorageCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Shelf", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Storage", "StorageCodeNavigation")
                        .WithMany("Shelves")
                        .HasForeignKey("StorageCode")
                        .HasConstraintName("FK__Shelf__StorageCo__5CD6CB2B");

                    b.Navigation("StorageCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Storage", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Building", "BuildingCodeNavigation")
                        .WithMany("Storages")
                        .HasForeignKey("BuildingCode")
                        .HasConstraintName("FK__Storage__Buildin__5535A963");

                    b.HasOne("ASMS.Repositories.Entities.ProductType", "ProductType")
                        .WithMany("Storages")
                        .HasForeignKey("ProductTypeId")
                        .HasConstraintName("FK__Storage__Product__571DF1D5");

                    b.HasOne("ASMS.Repositories.Entities.StorageType", "StorageType")
                        .WithMany("Storages")
                        .HasForeignKey("StorageTypeId")
                        .HasConstraintName("FK__Storage__Storage__5629CD9C");

                    b.Navigation("BuildingCodeNavigation");

                    b.Navigation("ProductType");

                    b.Navigation("StorageType");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.StorageBlock", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Storage", "StorageCodeNavigation")
                        .WithMany("StorageBlocks")
                        .HasForeignKey("StorageCode")
                        .HasConstraintName("FK__StorageBl__Stora__59FA5E80");

                    b.Navigation("StorageCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.TrackingHistory", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.Order", "OrderCodeNavigation")
                        .WithMany("TrackingHistories")
                        .HasForeignKey("OrderCode")
                        .HasConstraintName("FK__TrackingH__Order__778AC167");

                    b.Navigation("OrderCodeNavigation");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowStep", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("WorkflowTemplateId")
                        .HasConstraintName("FK__WorkflowS__Workf__4E88ABD4");

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowTemplate", b =>
                {
                    b.HasOne("ASMS.Repositories.Entities.StorageType", "StorageType")
                        .WithMany("WorkflowTemplates")
                        .HasForeignKey("StorageTypeId")
                        .HasConstraintName("FK__WorkflowT__Stora__4BAC3F29");

                    b.Navigation("StorageType");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Building", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Storages");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Container", b =>
                {
                    b.Navigation("ContainerLocationLogs");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.EmployeeRole", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Floor", b =>
                {
                    b.Navigation("Containers");

                    b.Navigation("FloorBlocks");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("TrackingHistories");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.ProductType", b =>
                {
                    b.Navigation("ContainerTypes");

                    b.Navigation("Storages");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Service", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Shelf", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.Storage", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Shelves");

                    b.Navigation("StorageBlocks");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.StorageType", b =>
                {
                    b.Navigation("Storages");

                    b.Navigation("WorkflowTemplates");
                });

            modelBuilder.Entity("ASMS.Repositories.Entities.WorkflowTemplate", b =>
                {
                    b.Navigation("WorkflowSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
